server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/portfolio
spring.datasource.username=portfolio
spring.datasource.password=portfolio
app.admin.token=${ADMIN_TOKEN:mi-token-super-seguro}
app.cors.public-origins=${CORS_PUBLIC_ORIGINS:http://localhost:3000,https://portfolio-web-orpin-three.vercel.app}
app.cors.admin-origins=${CORS_ADMIN_ORIGINS:http://localhost:3000,https://portfolio-web-orpin-three.vercel.app}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
