spring.application.name=portfolio-api
server.port=${PORT:8085}

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
app.admin.token=${ADMIN_TOKEN:}
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
