spring.application.name=portfolio-api
server.port=${PORT:8085}

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/api-docs
app.admin.token=${ADMIN_TOKEN:}
app.cors.public-origins=${CORS_PUBLIC_ORIGINS:http://localhost:3000}
app.cors.admin-origins=${CORS_ADMIN_ORIGINS:http://localhost:3000}
server.forward-headers-strategy=framework
spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info
